[package]
name = "xpack-platform"
description = "Cross-process locking, process launching and OS integration for xPack."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
reflink-copy.workspace = true
xpack-core.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
